In [7]:
import numpy as np

np.array([[1, 2, 3],[4, 5, 6]])
np.array(range(5))
np.array(i for i in range(10,100))

#range
print(list(range(5,10))) #list
print(np.arange(5,10)) #np.array

[5, 6, 7, 8, 9]
[5 6 7 8 9]


In [11]:
arr = np.zeros((5,5)) # x축, y축
arr2 = np.ones_like(arr) # array type data
print(arr)
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
print(np.linspace(10,20,5)) # linspace와 arange차이 알고있기
print(np.arange(10,20,5)) 

[10.  12.5 15.  17.5 20. ]
[10 15]


## Getting Information and Changing Shapes

In [16]:
np.arange(1,5).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [20]:
arr1 = np.arange(0,4).reshape((2,2))
arr2 = np.arange(4,8).reshape((2,2))

print(arr1, )
print(arr2)
print("\n\n")
print(np.dot(arr1,arr2))
print(np.inner(arr1,arr2))

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]



[[ 6  7]
 [26 31]]
[[ 5  7]
 [23 33]]


In [18]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[11, 12],[13, 14]])

print(a+b)
print(a-b)
print(np.dot(a,b))
print(np.inner(a, b))

[[12 14]
 [16 18]]
[[-10 -10]
 [-10 -10]]
[[37 40]
 [85 92]]
[[35 41]
 [81 95]]


In [ ]:
import pandas as pd

iris = pd.read_csv()